# Generated by Django 3.2.6 on 2021-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=3, max_digits=5)),
                ('time', models.SmallIntegerField()),
            ],
        ),
    ]
